name: Sync Registry
on: 
  push:
    branches: ['main']
jobs:
  build-with-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64 
    - name: Sync From Docker Hub to Aliyun
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: docker.io/tonistiigi/binfmt:qemu-v8.1.5
        source_username: ${{ secrets.DOCKER_USERNAME }}
        source_password: ${{ secrets.DOCKER_PASSWORD }}
        target_repository: heywhale-registry.cn-shanghai.cr.aliyuncs.com/aliyun-kesci/tonistiigi/binfmt:qemu-v8.1.5-arm64
        target_username: ${{ secrets.KESCI_ALIYUN_USERNAME }}
        target_password: ${{ secrets.KESCI_ALIYUN_PASSWORD }}
    
  build-with-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Sync From Docker Hub to Aliyun
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: docker.io/tonistiigi/binfmt:qemu-v8.1.5
        source_username: ${{ secrets.DOCKER_USERNAME }}
        source_password: ${{ secrets.DOCKER_PASSWORD }}
        target_repository: heywhale-registry.cn-shanghai.cr.aliyuncs.com/aliyun-kesci/tonistiigi/binfmt:qemu-v8.1.5-amd64
        target_username: ${{ secrets.KESCI_ALIYUN_USERNAME }}
        target_password: ${{ secrets.KESCI_ALIYUN_PASSWORD }}
  
  build-with-builds:
    runs-on: ubuntu-latest
    needs: [build-with-arm64, build-with-amd64]
    steps:
      - name: create docker manifest images for multiple platforms
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          context: .
          tags: tonistiigi/binfmt:qemu-v8.1.5
          platforms: linux/amd64,linux/arm64
          buildx_args: --push
