name: Sync Registry
on: 
  push:
    branches: ['master']
jobs:
  build-with-arm64:
    runs-on: macos-latest
    steps:
    - name: Sync From Docker Hub to Aliyun
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: docker.io/gitlab/gitlab-runner-helper:arm64-latest
        source_username: ${{ secrets.DOCKER_USERNAME }}
        source_password: ${{ secrets.DOCKER_PASSWORD }}
        target_repository: heywhale-registry.cn-shanghai.cr.aliyuncs.com/aliyun-kesci/gitlab-runner-helper:arm64-latest
        target_username: ${{ secrets.KESCI_ALIYUN_USERNAME }}
        target_password: ${{ secrets.KESCI_ALIYUN_PASSWORD }}